title: CasieBarie Development
description: >-
  Developer portfolio of CasieBarie. Explore Minecraft plugins, Discord bots, and creative projects.
author:
  name: Cas Barnard
  email: casiebarie@gmail.com
lang: en
baseurl: ""
url: "https://www.casiebarie.dev"
github_username: CasieBarie
permalink: pretty
include:
  - .well-known

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from

sass:
  sass_dir: _sass
  style: compressed

navigation:
  - title: HOME
    url: /
    fa: icon-house
  - title: MINECRAFT PROJECTS
    url: /minecraft/
    fa: icon-cubes
  - title: DISCORD BOTS
    url: /discord/
    fa: icon-discord
  - title: OTHER PROJECTS
    url: /other/
    fa: icon-bars-progress
  - title: ABOUT ME
    url: /aboutme
    fa: icon-user-large

seo:
  type: "website"
  name: "CasieBarie Development"
  description: "Developer portfolio of CasieBarie. Explore Minecraft plugins, Discord bots, and creative projects."
  url: "https://www.casiebarie.dev"
  logo: "/assets/images/mascot.webp"
  twitter:
    username: "CasieBarie"
    card: "summary_large_image"
  github: "CasieBarie"